// Service label detection from URL
export function detectServiceLabel(url: string): string {
  const lowered = url.toLowerCase()

  // Global services
  if (lowered.includes('github.com')) return 'GitHub'
  if (lowered.includes('twitter.com') || lowered.includes('x.com')) return 'Twitter'
  if (lowered.includes('youtube.com') || lowered.includes('youtu.be')) return 'YouTube'
  if (lowered.includes('instagram.com')) return 'Instagram'
  if (lowered.includes('linkedin.com')) return 'LinkedIn'
  if (lowered.includes('facebook.com')) return 'Facebook'
  if (lowered.includes('bsky.app')) return 'Bluesky'
  if (lowered.includes('twitch.tv')) return 'Twitch'
  if (lowered.includes('discord.gg') || lowered.includes('discord.com')) return 'Discord'
  if (lowered.includes('reddit.com')) return 'Reddit'
  if (lowered.includes('medium.com')) return 'Medium'
  if (lowered.includes('substack.com')) return 'Substack'
  if (lowered.includes('tiktok.com')) return 'TikTok'
  if (lowered.includes('threads.net')) return 'Threads'
  if (lowered.includes('mastodon.') || lowered.includes('mstdn.')) return 'Mastodon'
  if (lowered.includes('gitlab.com')) return 'GitLab'
  if (lowered.includes('bitbucket.org')) return 'Bitbucket'
  if (lowered.includes('stackoverflow.com')) return 'Stack Overflow'
  if (lowered.includes('dev.to')) return 'DEV'
  if (lowered.includes('hashnode.')) return 'Hashnode'
  if (lowered.includes('patreon.com')) return 'Patreon'
  if (lowered.includes('ko-fi.com')) return 'Ko-fi'
  if (lowered.includes('buymeacoffee.com')) return 'Buy Me a Coffee'
  if (lowered.includes('paypal.me') || lowered.includes('paypal.com')) return 'PayPal'
  if (lowered.includes('spotify.com')) return 'Spotify'
  if (lowered.includes('soundcloud.com')) return 'SoundCloud'
  if (lowered.includes('bandcamp.com')) return 'Bandcamp'
  if (lowered.includes('apple.com/music') || lowered.includes('music.apple.com')) return 'Apple Music'
  if (lowered.includes('dribbble.com')) return 'Dribbble'
  if (lowered.includes('behance.net')) return 'Behance'
  if (lowered.includes('figma.com')) return 'Figma'
  if (lowered.includes('codepen.io')) return 'CodePen'
  if (lowered.includes('producthunt.com')) return 'Product Hunt'
  if (lowered.includes('goodreads.com')) return 'Goodreads'
  if (lowered.includes('letterboxd.com')) return 'Letterboxd'
  if (lowered.includes('pinterest.com') || lowered.includes('pinterest.jp')) return 'Pinterest'
  if (lowered.includes('tumblr.com')) return 'Tumblr'
  if (lowered.includes('vimeo.com')) return 'Vimeo'
  if (lowered.includes('dailymotion.com')) return 'Dailymotion'
  if (lowered.includes('telegram.me') || lowered.includes('t.me')) return 'Telegram'
  if (lowered.includes('signal.org')) return 'Signal'
  if (lowered.includes('whatsapp.com')) return 'WhatsApp'
  if (lowered.includes('line.me')) return 'LINE'
  if (lowered.includes('wechat.com')) return 'WeChat'
  if (lowered.includes('snapchat.com')) return 'Snapchat'
  if (lowered.includes('steam')) return 'Steam'
  if (lowered.includes('itch.io')) return 'itch.io'
  if (lowered.includes('finalfantasyxiv.com')) return 'FF14'
  if (lowered.includes('playstation.com')) return 'PlayStation'
  if (lowered.includes('xbox.com')) return 'Xbox'
  if (lowered.includes('nintendo.')) return 'Nintendo'
  if (lowered.includes('gumroad.com')) return 'Gumroad'
  if (lowered.includes('notion.so') || lowered.includes('notion.site')) return 'Notion'
  if (lowered.includes('opensea.io')) return 'OpenSea'
  if (lowered.includes('amazon.')) return 'Amazon'
  if (lowered.includes('etsy.com')) return 'Etsy'

  // Japanese services
  if (lowered.includes('qiita.com')) return 'Qiita'
  if (lowered.includes('zenn.dev')) return 'Zenn'
  if (lowered.includes('note.com')) return 'note'
  if (lowered.includes('hatenablog.com') || lowered.includes('hatenadiary.')) return 'はてなブログ'
  if (lowered.includes('b.hatena.ne.jp')) return 'はてブ'
  if (lowered.includes('hatena.ne.jp')) return 'はてな'
  if (lowered.includes('pixiv.net')) return 'Pixiv'
  if (lowered.includes('fanbox.cc')) return 'FANBOX'
  if (lowered.includes('booth.pm')) return 'BOOTH'
  if (lowered.includes('nicovideo.jp') || lowered.includes('nico.ms')) return 'ニコニコ'
  if (lowered.includes('mixi.jp')) return 'mixi'
  if (lowered.includes('mixi2.us')) return 'mixi2'
  if (lowered.includes('ameblo.jp') || lowered.includes('ameba.jp')) return 'Ameba'
  if (lowered.includes('fc2.com')) return 'FC2'
  if (lowered.includes('livedoor.jp') || lowered.includes('blog.jp')) return 'livedoor'
  if (lowered.includes('cocolog-nifty.com')) return 'ココログ'
  if (lowered.includes('connpass.com')) return 'connpass'
  if (lowered.includes('doorkeeper.jp')) return 'Doorkeeper'
  if (lowered.includes('wantedly.com')) return 'Wantedly'
  if (lowered.includes('speakerdeck.com')) return 'Speaker Deck'
  if (lowered.includes('slideshare.net')) return 'SlideShare'
  if (lowered.includes('lit.link')) return 'lit.link'
  if (lowered.includes('linktr.ee')) return 'Linktree'
  if (lowered.includes('potofu.me')) return 'POTOFU'
  if (lowered.includes('suzuri.jp')) return 'SUZURI'
  if (lowered.includes('minne.com')) return 'minne'
  if (lowered.includes('creema.jp')) return 'Creema'
  if (lowered.includes('stores.jp')) return 'STORES'
  if (lowered.includes('base.shop') || lowered.includes('thebase.in')) return 'BASE'
  if (lowered.includes('mercari.com')) return 'メルカリ'
  if (lowered.includes('rakuten.co.jp')) return '楽天'
  if (lowered.includes('yahoo.co.jp')) return 'Yahoo! JAPAN'
  if (lowered.includes('showroom-live.com')) return 'SHOWROOM'
  if (lowered.includes('17live.jp') || lowered.includes('17.live')) return '17LIVE'
  if (lowered.includes('pococha.com')) return 'Pococha'
  if (lowered.includes('bilibili.com')) return 'bilibili'

  return 'Website'
}
